### ISSUE TITLE
Problems with running install command - doesn't seem to be able to install .prello directory in home folder

### ISSUE THREAD

**Issue by erback** [campusbokhandeln/prello#3]
<img width="780" alt="Screen Shot 2021-11-02 at 7 21 20 PM" src="https://user-images.githubusercontent.com/7672362/139923061-3a035faa-4659-435f-adbd-28c9c2a7ee1e.png">

**Comment by argia-andreas** [comment]
@erback 
Could you check if this if fixed in the brand new release of Prello v0.0.4?

It works on my computer...

**Comment by erback** [comment]
works like a charm now in version v.0.0.8
